name: Question
description: Ask a question
title: "[Question] Question title"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: >
        Advanced/nontrivial questions, especially in areas where
        documentation is lacking, are very much welcome.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question
    validations:
      required: true
